### ISSUE TITLE
cnext-init error 

### ISSUE THREAD

**Issue by hanghust** [cnextio/cnext#3]
I'm trying run "cnext-init" on windows and I'm getting an error "No module readline"
Setup specs:
Windows 10
Python v3.9.12

**Comment by hanghust** [comment]
Windows 10
Python v3.10
Error shows when using pip installation method at step cnext-init
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1776.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\GPPM\cnextenv\Scripts\cnext-init.exe\__main__.py", line 4, in <module>
  File "C:\Users\GPPM\cnextenv\lib\site-packages\cnext_server\__main__.py", line 18, in <module>
    readline = Readline()
  File "C:\Users\GPPM\cnextenv\lib\site-packages\pyreadline\rlmain.py", line 422, in __init__
    BaseReadline.__init__(self)
  File "C:\Users\GPPM\cnextenv\lib\site-packages\pyreadline\rlmain.py", line 62, in __init__
    mode.init_editing_mode(None)
  File "C:\Users\GPPM\cnextenv\lib\site-packages\pyreadline\modes\emacs.py", line 633, in init_editing_mode
    self._bind_key('space',       self.self_insert)
  File "C:\Users\GPPM\cnextenv\lib\site-packages\pyreadline\modes\basemode.py", line 162, in _bind_key
    if not callable(func):
  File "C:\Users\GPPM\cnextenv\lib\site-packages\pyreadline\py3k_compat.py", line 8, in callable
    return isinstance(x, collections.Callable)
AttributeError: module 'collections' has no attribute 'Callable'
